### ISSUE TITLE
Can't run bundle update on jruby with gem pointed to git repo

### ISSUE THREAD

**Issue by zoras** [bundler/bundler#6174]
`bundle update` works with `mri ruby 2.4.2` and also worked fine in previous bundler version and `jruby-9.1.14.0` but is breaks with `bundler -v 1.16.0`

```
❯ jruby -v
jruby 9.1.14.0 (2.3.3) 2017-11-08 2176f24 Java HotSpot(TM) 64-Bit Server VM 9.0.1+11 on 9.0.1+11 [darwin-x86_64]
```

```
❯ bundle update
Fetching https://github.com/thoughtbot/paperclip.git
c794f6df0a10b94f377b9efea08dcfa4e73cfc43
HEAD is now at c794f6d Be more explicit
git version 2.15.0
git version 2.15.0
rbenv 1.1.1
fatal: Not a git repository (or any of the parent directories): .git
```

## Backtrace

```
NoMethodError: undefined method `[]' for nil:NilClass
  /Users/zoras/.rbenv/versions/jruby-9.1.14.0/lib/ruby/stdlib/bundler/source/git/git_proxy.rb:86:in `version'
  /Users/zoras/.rbenv/versions/jruby-9.1.14.0/lib/ruby/stdlib/bundler/source/git/git_proxy.rb:138:in `block in copy_to'
  org/jruby/RubyDir.java:323:in `chdir'
  /Users/zoras/.rbenv/versions/jruby-9.1.14.0/lib/ruby/stdlib/bundler/shared_helpers.rb:65:in `block in chdir'
  /Users/zoras/.rbenv/versions/jruby-9.1.14.0/lib/ruby/stdlib/monitor.rb:214:in `mon_synchronize'
  /Users/zoras/.rbenv/versions/jruby-9.1.14.0/lib/ruby/stdlib/bundler/shared_helpers.rb:64:in `chdir'
  /Users/zoras/.rbenv/versions/jruby-9.1.14.0/lib/ruby/stdlib/bundler/source/git/git_proxy.rb:132:in `copy_to'
  /Users/zoras/.rbenv/versions/jruby-9.1.14.0/lib/ruby/stdlib/bundler/source/git.rb:161:in `specs'
  /Users/zoras/.rbenv/versions/jruby-9.1.14.0/lib/ruby/stdlib/bundler/definition.rb:751:in `block in converge_locked_specs'
  org/jruby/RubyArray.java:1734:in `each'
  /Users/zoras/.rbenv/versions/jruby-9.1.14.0/lib/ruby/stdlib/bundler/definition.rb:737:in `converge_locked_specs'
  /Users/zoras/.rbenv/versions/jruby-9.1.14.0/lib/ruby/stdlib/bundler/definition.rb:247:in `resolve'
  /Users/zoras/.rbenv/versions/jruby-9.1.14.0/lib/ruby/stdlib/bundler/definition.rb:170:in `specs'
  /Users/zoras/.rbenv/versions/jruby-9.1.14.0/lib/ruby/stdlib/bundler/definition.rb:158:in `resolve_remotely!'
  /Users/zoras/.rbenv/versions/jruby-9.1.14.0/lib/ruby/stdlib/bundler/installer.rb:279:in `resolve_if_needed'
  /Users/zoras/.rbenv/versions/jruby-9.1.14.0/lib/ruby/stdlib/bundler/installer.rb:83:in `block in run'
  /Users/zoras/.rbenv/versions/jruby-9.1.14.0/lib/ruby/stdlib/bundler/process_lock.rb:12:in `block in lock'
  org/jruby/RubyIO.java:1156:in `open'
  /Users/zoras/.rbenv/versions/jruby-9.1.14.0/lib/ruby/stdlib/bundler/process_lock.rb:9:in `lock'
  /Users/zoras/.rbenv/versions/jruby-9.1.14.0/lib/ruby/stdlib/bundler/installer.rb:72:in `run'
  /Users/zoras/.rbenv/versions/jruby-9.1.14.0/lib/ruby/stdlib/bundler/installer.rb:25:in `install'
  /Users/zoras/.rbenv/versions/jruby-9.1.14.0/lib/ruby/stdlib/bundler/cli/update.rb:61:in `run'
  /Users/zoras/.rbenv/versions/jruby-9.1.14.0/lib/ruby/stdlib/bundler/cli.rb:266:in `update'
  /Users/zoras/.rbenv/versions/jruby-9.1.14.0/lib/ruby/stdlib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
  /Users/zoras/.rbenv/versions/jruby-9.1.14.0/lib/ruby/stdlib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
  /Users/zoras/.rbenv/versions/jruby-9.1.14.0/lib/ruby/stdlib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
  /Users/zoras/.rbenv/versions/jruby-9.1.14.0/lib/ruby/stdlib/bundler/cli.rb:27:in `dispatch'
  /Users/zoras/.rbenv/versions/jruby-9.1.14.0/lib/ruby/stdlib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
  /Users/zoras/.rbenv/versions/jruby-9.1.14.0/lib/ruby/stdlib/bundler/cli.rb:18:in `start'
  /Users/zoras/.rbenv/versions/jruby-9.1.14.0/lib/ruby/gems/shared/gems/bundler-1.16.0/exe/bundle:30:in `block in (root)'
  /Users/zoras/.rbenv/versions/jruby-9.1.14.0/lib/ruby/stdlib/bundler/friendly_errors.rb:122:in `with_friendly_errors'
  /Users/zoras/.rbenv/versions/jruby-9.1.14.0/lib/ruby/gems/shared/gems/bundler-1.16.0/exe/bundle:22:in `<main>'
  org/jruby/RubyKernel.java:973:in `load'
  ./bin/bundle:1:in `<main>'
```

## Environment

```
Bundler       1.16.0
  Platforms   ruby, universal-java-9
Ruby          2.3.3p0 (2017-11-08 revision 56859) [java]
  Full Path   /Users/zoras/.rbenv/versions/jruby-9.1.14.0/bin/jruby
  Config Dir  /Users/zoras/.rbenv/versions/jruby-9.1.14.0/etc
RubyGems      2.7.2
  Gem Home    /Users/zoras/.rbenv/versions/jruby-9.1.14.0/lib/ruby/gems/shared
  Gem Path    /Users/zoras/.rbenv/versions/jruby-9.1.14.0/lib/ruby/gems/shared:/Users/zoras/.gem/jruby/2.3.0
  User Path   /Users/zoras/.gem/jruby/2.3.0
  Bin Dir     /Users/zoras/.rbenv/versions/jruby-9.1.14.0/bin
OpenSSL
  Compiled    JRuby-OpenSSL 0.9.21
  Loaded      JRuby-OpenSSL 0.9.21
  Cert File   /Library/Java/JavaVirtualMachines/jdk-9.0.1.jdk/Contents/Home/lib/security/cacerts
  Cert Dir    /etc/ssl/certs
Tools
  Git
  RVM         not installed
  rbenv
  chruby      not installed
```

**Comment by colby-swandale** [comment]
Can you please share the output of `bundle env`?

**Comment by colby-swandale** [comment]
ping @zoras

**Comment by zoras** [comment]
@colby-swandale Thanks for the reminder.
I have reverted back to Java 8 and everything works fine. This is surely an issue with Java 9, jruby & bundler https://github.com/jruby/jruby/issues?q=is%3Aissue+is%3Aopen+label%3A"JDK+compatibility"

**Comment by colby-swandale** [comment]
Thanks
