### PR TITLE
Check if source responds to `#remotes` before printing gem install error message

### PR DESCRIPTION
**Pull request by colby-swandale**
### What was the end-user problem that led to this PR?

There is a bug that was introduced in #6211 that prints an error message during `bundle install` if a gem failed to be installed. The error message attempts to call the `#remotes` method on `Bundler::Source::Git` which it does not implement.

### What was your diagnosis of the problem?

See #6563

### What is your fix for the problem, implemented in this PR?

Check if the `source` responds to `#remotes` before and return early

### Why did you choose this fix out of the possible options?

This seems to be the most simplest fix without having to refactor a lot of code.

### CODE REVIEW

**Comment by indirect** [comment]
good catch! @bundlerbot r+
