### ISSUE TITLE
Odd errors after upgrading to 1.14.5

### ISSUE THREAD

**Issue by aliuk2012** [bundler/bundler#5492]
Hi,

I'm using rails 5 and recently updated from bundle 1.13.6 to 1.14.5 and ran into some issues. Two others devs on my team have also updated from various versions to 1.14.5 and they are experience the same errors.

Trying to access 
```
$ bundle exec rails c --trace
/Users/alaing/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/spring-1.7.2/lib/spring/application.rb:108:in `ensure in preload': undefined method `application' for Rails:Module (NoMethodError)
        from /Users/alaing/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/spring-1.7.2/lib/spring/application.rb:112:in `preload'
        from /Users/alaing/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/spring-1.7.2/lib/spring/application.rb:143:in `serve'
        from /Users/alaing/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/spring-1.7.2/lib/spring/application.rb:131:in `block in run'
        from /Users/alaing/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/spring-1.7.2/lib/spring/application.rb:125:in `loop'
        from /Users/alaing/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/spring-1.7.2/lib/spring/application.rb:125:in `run'
        from /Users/alaing/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/spring-1.7.2/lib/spring/application/boot.rb:19:in `<top (required)>'
        from /Users/alaing/.rbenv/versions/2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /Users/alaing/.rbenv/versions/2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from -e:1:in `<main>'

```
And 

Trying to run a task:

```
$ bundle exec rails users:demo_entries --trace
rails aborted!
NameError: undefined method `+' for class `Date'
/Users/alaing/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.1/lib/active_support/core_ext/date/calculations.rb:95:in `alias_method'
/Users/alaing/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.1/lib/active_support/core_ext/date/calculations.rb:95:in `<class:Date>'
/Users/alaing/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.1/lib/active_support/core_ext/date/calculations.rb:8:in `<top (required)>'
/Users/alaing/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.1/lib/active_support/core_ext/time/calculations.rb:6:in `require'
/Users/alaing/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.1/lib/active_support/core_ext/time/calculations.rb:6:in `<top (required)>'
/Users/alaing/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.1/lib/active_support/file_update_checker.rb:1:in `require'
/Users/alaing/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.1/lib/active_support/file_update_checker.rb:1:in `<top (required)>'
/Users/alaing/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.1/lib/active_support/i18n_railtie.rb:2:in `require'
/Users/alaing/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.1/lib/active_support/i18n_railtie.rb:2:in `<top (required)>'
/Users/alaing/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.1/lib/active_support/railtie.rb:2:in `require'
/Users/alaing/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.1/lib/active_support/railtie.rb:2:in `<top (required)>'
/Users/alaing/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.0.1/lib/rails.rb:14:in `require'
/Users/alaing/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.0.1/lib/rails.rb:14:in `<top (required)>'
/Users/alaing/Work/correspondence_tool_staff/config/application.rb:3:in `require'
/Users/alaing/Work/correspondence_tool_staff/config/application.rb:3:in `<top (required)>'
/Users/alaing/Work/correspondence_tool_staff/Rakefile:4:in `require_relative'
/Users/alaing/Work/correspondence_tool_staff/Rakefile:4:in `<top (required)>'
/Users/alaing/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-11.3.0/lib/rake/rake_module.rb:28:in `load'
/Users/alaing/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-11.3.0/lib/rake/rake_module.rb:28:in `load_rakefile'
/Users/alaing/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-11.3.0/lib/rake/application.rb:686:in `raw_load_rakefile'
/Users/alaing/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-11.3.0/lib/rake/application.rb:96:in `block in load_rakefile'
/Users/alaing/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-11.3.0/lib/rake/application.rb:178:in `standard_exception_handling'
/Users/alaing/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-11.3.0/lib/rake/application.rb:95:in `load_rakefile'
/Users/alaing/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.0.1/lib/rails/commands/rake_proxy.rb:13:in `block in run_rake_task'
/Users/alaing/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-11.3.0/lib/rake/application.rb:178:in `standard_exception_handling'
/Users/alaing/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.0.1/lib/rails/commands/rake_proxy.rb:11:in `run_rake_task'
/Users/alaing/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.0.1/lib/rails/commands/commands_tasks.rb:51:in `run_command!'
/Users/alaing/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.0.1/lib/rails/commands.rb:18:in `<top (required)>'
/Users/alaing/Work/correspondence_tool_staff/bin/rails:9:in `require'
/Users/alaing/Work/correspondence_tool_staff/bin/rails:9:in `<top (required)>'
/Users/alaing/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/spring-1.7.2/lib/spring/client/rails.rb:28:in `load'
/Users/alaing/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/spring-1.7.2/lib/spring/client/rails.rb:28:in `call'
/Users/alaing/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/spring-1.7.2/lib/spring/client/command.rb:7:in `call'
/Users/alaing/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/spring-1.7.2/lib/spring/client.rb:30:in `run'
/Users/alaing/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/spring-1.7.2/bin/spring:49:in `<top (required)>'
/Users/alaing/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/spring-1.7.2/lib/spring/binstub.rb:11:in `load'
/Users/alaing/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/spring-1.7.2/lib/spring/binstub.rb:11:in `<top (required)>'
/Users/alaing/Work/correspondence_tool_staff/bin/spring:13:in `require'
/Users/alaing/Work/correspondence_tool_staff/bin/spring:13:in `<top (required)>'
bin/rails:3:in `load'
bin/rails:3:in `<main>'

```

We have now reverted back to 1.14.4 and are now able to run these commands.

We have also  had to run ```$ spring stop``` a between upgrading/downgrading.

**Comment by colby-swandale** [comment]
hi @aliuk2012, do you have a repo that we can use to reproduce the errors you're encountering.

**Comment by aliuk2012** [comment]
Hi @colby-swandale ,Sure this is the repo which we are having problems on. https://github.com/ministryofjustice/correspondence_tool_staff

**Comment by colby-swandale** [comment]
Thanks for providing the repo, i was able to reproduce the issue you reported on the latest bundler release but this problem seems specific to your project. I was unable to reproduce the same error on a new rails `5.0.1` project.

**Comment by aliuk2012** [comment]
Thanks for confirming, I wonder if its a spring issue thats causing it. This application was created using rails 5.0 and has updated as new versions became available.

**Comment by akostadinov** [comment]
I also see same issue running `rails test` in our app. Strange because the only thing I did was upgrade my machine and `bundle update`. So not sure what exactly could have caused this.

**Comment by ghfr** [comment]
I have the same problem, and adding json to Gemfile did not work. Can someone help me ?

rails generate model user
/home/thomasleoty/.rvm/gems/ruby-2.5.1/gems/spring-2.0.2/lib/spring/application.rb:118:in `ensure in preload': undefined method `application' for Rails:Module (NoMethodError)
	from /home/thomasleoty/.rvm/gems/ruby-2.5.1/gems/spring-2.0.2/lib/spring/application.rb:122:in `preload'
	from /home/thomasleoty/.rvm/gems/ruby-2.5.1/gems/spring-2.0.2/lib/spring/application.rb:153:in `serve'
	from /home/thomasleoty/.rvm/gems/ruby-2.5.1/gems/spring-2.0.2/lib/spring/application.rb:141:in `block in run'
	from /home/thomasleoty/.rvm/gems/ruby-2.5.1/gems/spring-2.0.2/lib/spring/application.rb:135:in `loop'
	from /home/thomasleoty/.rvm/gems/ruby-2.5.1/gems/spring-2.0.2/lib/spring/application.rb:135:in `run'
	from /home/thomasleoty/.rvm/gems/ruby-2.5.1/gems/spring-2.0.2/lib/spring/application/boot.rb:19:in `<top (required)>'
	from /usr/share/rvm/rubies/ruby-2.5.1/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	from /usr/share/rvm/rubies/ruby-2.5.1/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	from -e:1:in `<main>'

GEMFILE : 
source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.5.1'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 5.2.1'
# Use sqlite3 as the database for Active Record
gem 'sqlite3'
# Use Puma as the app server
gem 'puma', '~> 3.11'
# Use SCSS for stylesheets
gem 'sass-rails', '~> 5.0'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# See https://github.com/rails/execjs#readme for more supported runtimes
# gem 'mini_racer', platforms: :ruby
gem 'json'
# Use CoffeeScript for .coffee assets and views
gem 'coffee-rails', '~> 4.2'
# Turbolinks makes navigating your web application faster. Read more: https://github.com/turbolinks/turbolinks
gem 'turbolinks', '~> 5'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.5'
# Use Redis adapter to run Action Cable in production
# gem 'redis', '~> 4.0'
# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use ActiveStorage variant
# gem 'mini_magick', '~> 4.8'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

# Reduces boot times through caching; required in config/boot.rb
gem 'bootsnap', '>= 1.1.0', require: false

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
end

group :development do
  # Access an interactive console on exception pages or by calling 'console' anywhere in the code.
  gem 'web-console', '>= 3.3.0'
  gem 'listen', '>= 3.0.5', '< 3.2'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
gem "spring", group: :development

  gem 'spring-watcher-listen', '~> 2.0.0'
end

group :test do
  # Adds support for Capybara system testing and selenium driver
  gem 'capybara', '>= 2.15'
  gem 'selenium-webdriver'
  # Easy installation and use of chromedriver to run system tests with Chrome
  gem 'chromedriver-helper'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
