### ISSUE TITLE
Bundler 1.3.2 doesn't work with Rubygems 2.0.2 and large gemfiles

### ISSUE THREAD

**Issue by deric** [bundler/bundler#2372]
I'm trying to run `bundle install` on Gentoo Linux 2.6.36 64bit

It looks like Bundler is unable to fetch data from RubyGems.

<pre>
~/.rvm/gems/ruby-2.0.0-p0/gems/bundler-1.3.2/lib/bundler/fetcher.rb:119:in `specs': undefined method `each' for nil:NilClass (NoMethodError)
        from ~/.rvm/gems/ruby-2.0.0-p0/gems/bundler-1.3.2/lib/bundler/source/rubygems.rb:244:in `block in remote_specs'
        from ~/.rvm/gems/ruby-2.0.0-p0/gems/bundler-1.3.2/lib/bundler/source/rubygems.rb:244:in `each'
        from ~/.rvm/gems/ruby-2.0.0-p0/gems/bundler-1.3.2/lib/bundler/source/rubygems.rb:244:in `remote_specs'
        from ~/.rvm/gems/ruby-2.0.0-p0/gems/bundler-1.3.2/lib/bundler/source/rubygems.rb:162:in `fetch_specs'
        from ~/.rvm/gems/ruby-2.0.0-p0/gems/bundler-1.3.2/lib/bundler/source/rubygems.rb:66:in `specs'
        from ~/.rvm/gems/ruby-2.0.0-p0/gems/bundler-1.3.2/lib/bundler/lazy_specification.rb:52:in `__materialize__'
        from ~/.rvm/gems/ruby-2.0.0-p0/gems/bundler-1.3.2/lib/bundler/spec_set.rb:88:in `block in materialize'
        from ~/.rvm/gems/ruby-2.0.0-p0/gems/bundler-1.3.2/lib/bundler/spec_set.rb:85:in `map!'
        from ~/.rvm/gems/ruby-2.0.0-p0/gems/bundler-1.3.2/lib/bundler/spec_set.rb:85:in `materialize'
        from ~/.rvm/gems/ruby-2.0.0-p0/gems/bundler-1.3.2/lib/bundler/definition.rb:114:in `specs'
        from ~/.rvm/gems/ruby-2.0.0-p0/gems/bundler-1.3.2/lib/bundler/definition.rb:109:in `resolve_remotely!'
        from ~/.rvm/gems/ruby-2.0.0-p0/gems/bundler-1.3.2/lib/bundler/installer.rb:83:in `run'
        from ~/.rvm/gems/ruby-2.0.0-p0/gems/bundler-1.3.2/lib/bundler/installer.rb:14:in `install'
        from ~/.rvm/gems/ruby-2.0.0-p0/gems/bundler-1.3.2/lib/bundler/cli.rb:248:in `install'
        from ~/.rvm/gems/ruby-2.0.0-p0/gems/bundler-1.3.2/lib/bundler/vendor/thor/task.rb:27:in `run'
        from ~/.rvm/gems/ruby-2.0.0-p0/gems/bundler-1.3.2/lib/bundler/vendor/thor/invocation.rb:120:in `invoke_task'
        from ~/.rvm/gems/ruby-2.0.0-p0/gems/bundler-1.3.2/lib/bundler/vendor/thor.rb:344:in `dispatch'
        from ~/.rvm/gems/ruby-2.0.0-p0/gems/bundler-1.3.2/lib/bundler/vendor/thor/base.rb:434:in `start'
        from ~/.rvm/gems/ruby-2.0.0-p0/gems/bundler-1.3.2/bin/bundle:20:in `block in <top (required)>'
        from ~/.rvm/gems/ruby-2.0.0-p0/gems/bundler-1.3.2/lib/bundler/friendly_errors.rb:3:in `with_friendly_errors'
        from ~/.rvm/gems/ruby-2.0.0-p0/gems/bundler-1.3.2/bin/bundle:20:in `<top (required)>'
        from ~/.rvm/gems/ruby-2.0.0-p0/bin/bundle:23:in `load'
        from ~/.rvm/gems/ruby-2.0.0-p0/bin/bundle:23:in `<main>'
        from ~/.rvm/gems/ruby-2.0.0-p0/bin/ruby_noexec_wrapper:14:in `eval'
        from ~/.rvm/gems/ruby-2.0.0-p0/bin/ruby_noexec_wrapper:14:in `<main>'
</pre>

on ruby 1.9.3-p374 everything is fine

any idea how to debug this?
