### ISSUE TITLE
Bundler 1.3.3 and Ruby 1.9.3 undefined method 'dump' for YAML::Module 

### ISSUE THREAD

**Issue by grossjo** [bundler/bundler#2393]
Trying to run a bundle install that works on bundler 1.3.2 fails on 1.3.3.  Error is below

   Unfortunately, a fatal error has occurred. Please see the Bundler
      troubleshooting documentation at http://bit.ly/bundler-issues. Thanks!
/var/lib/gems/1.9.1/gems/bundler-1.3.3/lib/bundler/settings.rb:129:in `block in set_key': undefined method`dump' for YAML:Module (NoMethodError)
    from /var/lib/gems/1.9.1/gems/bundler-1.3.3/lib/bundler/settings.rb:129:in `open'
    from /var/lib/gems/1.9.1/gems/bundler-1.3.3/lib/bundler/settings.rb:129:in`set_key'
    from /var/lib/gems/1.9.1/gems/bundler-1.3.3/lib/bundler/settings.rb:17:in `[]='
    from /var/lib/gems/1.9.1/gems/bundler-1.3.3/lib/bundler/cli.rb:218:in`install'
    from /var/lib/gems/1.9.1/gems/bundler-1.3.3/lib/bundler/vendor/thor/task.rb:27:in `run'
    from /var/lib/gems/1.9.1/gems/bundler-1.3.3/lib/bundler/vendor/thor/invocation.rb:120:in`invoke_task'
    from /var/lib/gems/1.9.1/gems/bundler-1.3.3/lib/bundler/vendor/thor.rb:344:in `dispatch'
    from /var/lib/gems/1.9.1/gems/bundler-1.3.3/lib/bundler/vendor/thor/base.rb:434:in`start'
    from /var/lib/gems/1.9.1/gems/bundler-1.3.3/bin/bundle:20:in `block in <top (required)>'
    from /var/lib/gems/1.9.1/gems/bundler-1.3.3/lib/bundler/friendly_errors.rb:3:in`with_friendly_errors'
    from /var/lib/gems/1.9.1/gems/bundler-1.3.3/bin/bundle:20:in `<top (required)>'
    from /usr/local/bin/bundle:19:in`load'
    from /usr/local/bin/bundle:19:in `<main>'
