### ISSUE TITLE
#quiet? not defined on Bundler::UI

### ISSUE THREAD

**Issue by pivotalcommon** [bundler/bundler#2460]
We're receiving:

```
undefined method `quiet?' for #<Bundler::UI:0x007fecb1479b68>
/Users/pivotal/.rvm/gems/ruby-2.0.0-p0/gems/bundler-1.3.5/lib/bundler/source/git/git_proxy.rb:48:in `checkout'
/Users/pivotal/.rvm/gems/ruby-2.0.0-p0/gems/bundler-1.3.5/lib/bundler/source/git.rb:144:in `specs'
/Users/pivotal/.rvm/gems/ruby-2.0.0-p0/gems/bundler-1.3.5/lib/bundler/lazy_specification.rb:52:in `__materialize__'
/Users/pivotal/.rvm/gems/ruby-2.0.0-p0/gems/bundler-1.3.5/lib/bundler/spec_set.rb:88:in `block in materialize'
/Users/pivotal/.rvm/gems/ruby-2.0.0-p0/gems/bundler-1.3.5/lib/bundler/spec_set.rb:85:in `map!'
/Users/pivotal/.rvm/gems/ruby-2.0.0-p0/gems/bundler-1.3.5/lib/bundler/spec_set.rb:85:in `materialize'
/Users/pivotal/.rvm/gems/ruby-2.0.0-p0/gems/bundler-1.3.5/lib/bundler/definition.rb:114:in `specs'
/Users/pivotal/.rvm/gems/ruby-2.0.0-p0/gems/bundler-1.3.5/lib/bundler/definition.rb:109:in `resolve_remotely!'
```

when we're access definitions (and their dependencies) programmatically (not via the CLI) using:

```
definition = Bundler::Definition.build(gemfile_path, gemfile_lock_path, nil)
definition.resolve_remotely!
```

and the gemfile contains a git sourced gem.

It looks like this was introduced by https://github.com/carlhuda/bundler/pull/2194. We were going to patch this, but we unclear where the test for this should go? If someone with experience on the code base has pointers, we'll be happy to patch.

Thanks!
