### ISSUE TITLE
Building native extensions.  This could take a while... ERROR:  Error installing json: 	ERROR: Failed to build gem native extension.

### ISSUE THREAD

**Issue by SerjB** [bundler/bundler#5347]
Error details:
````
gem install json -v '1.8.3'
Building native extensions.  This could take a while...
ERROR:  Error installing json:
	ERROR: Failed to build gem native extension.

    current directory: /home/serj/.rvm/gems/ruby-2.4.0/gems/json-1.8.3/ext/json/ext/generator
/home/serj/.rvm/rubies/ruby-2.4.0/bin/ruby -r ./siteconf20170122-6097-3qmkav.rb extconf.rb
creating Makefile

current directory: /home/serj/.rvm/gems/ruby-2.4.0/gems/json-1.8.3/ext/json/ext/generator
make "DESTDIR=" clean

current directory: /home/serj/.rvm/gems/ruby-2.4.0/gems/json-1.8.3/ext/json/ext/generator
make "DESTDIR="
compiling generator.c
generator.c: In function ‘generate_json’:
generator.c:861:25: error: ‘rb_cFixnum’ undeclared (first use in this function)
     } else if (klass == rb_cFixnum) {
                         ^
generator.c:861:25: note: each undeclared identifier is reported only once for each function it appears in
generator.c:863:25: error: ‘rb_cBignum’ undeclared (first use in this function)
     } else if (klass == rb_cBignum) {
                         ^
generator.c: At top level:
cc1: warning: unrecognized command line option "-Wno-self-assign" [enabled by default]
cc1: warning: unrecognized command line option "-Wno-constant-logical-operand" [enabled by default]
cc1: warning: unrecognized command line option "-Wno-parentheses-equality" [enabled by default]
cc1: warning: unrecognized command line option "-Wno-tautological-compare" [enabled by default]
make: *** [generator.o] Error 1

make failed, exit code 2

Gem files will remain installed in /home/serj/.rvm/gems/ruby-2.4.0/gems/json-1.8.3 for inspection.
Results logged to /home/serj/.rvm/gems/ruby-2.4.0/extensions/x86_64-linux/2.4.0/json-1.8.3/gem_make.out
`

```

**Comment by segiddins** [comment]
JSON 1.8.3 doesn't work with ruby 2.4, you have to update to 1.8.5
