### PR TITLE
Closes #3558

### LINKED ISSUE #3558: NoMethodError: undefined method `spec' for nil:NilClass
That exception occurs when running `bundle install` on the current `ruby-head` ...
Have found this twice so far, and suspect I'll keep finding it if I keep looking:

* abstractive/rspec-log_split#2
* celluloid/timers#47

### PR DESCRIPTION
**Pull request by digitalextremist**
`ruby-head` seems to be more strict about how instance variables are referenced, at the moment.

### CODE REVIEW

**Comment by segiddins** [comment]
I believe this is actually caused by https://github.com/rubygems/rubygems/commit/620910aa75c7446e8f8d5af1df5f981e4da86197.

**Comment by segiddins** [comment]
@digitalextremist this PR doesn't seem to fix things, please take a look at the test failures?

**Comment by digitalextremist** [comment]
@segiddins seeing the test failures, but at first glance it seems like it's failing on tests *not* anticipating @tenderlove's changes to rubygems. Looking further.

**Comment by digitalextremist** [comment]
@segiddins the give-away that this is more about how an instance variable is referenced versus whether caching is being done, for me, is that this is `ruby-head` isolated so far.

**Comment by segiddins** [comment]
well, does adding an `attr_accessor :spec` fix things?

**Comment by digitalextremist** [comment]
I pulled my comment from @tenderlove's commit since it was out of the context of that commit, and I'm looking through rubygems right now to attempt putting `@spec` within scope of its own instances which reference it as `spec` .. purely for science, because you asked. As far as I can see, what you're talking about is *another* similar issue.

**Comment by indirect** [comment]
I have basically no idea what is even going on here. What is broken, and under what circumstances? What is this patch supposed to fix, and why does the change make the tests fail?

**Comment by indirect** [comment]
This is fixed by f4481a7e3dbaf7f563e32afbe2cbbb84e3091f16.
