### ISSUE TITLE
bundler/capistrano doesn't work with capistrano 3.0.0

### ISSUE THREAD

**Issue by jcoyne** [bundler/bundler#2674]
In my config/deploy.rb I have

```
require 'bundler/capistrano'
```

Here's the error:

```
cap sandbox deploy
cap aborted!
undefined method `instance' for Capistrano::Configuration:Class
/Users/justin/.rvm/gems/ruby-2.0.0-p247/gems/bundler-1.4.0.rc.1/lib/bundler/capistrano.rb:11:in `<top (required)>'
config/deploy.rb:1:in `<top (required)>'
/Users/justin/.rvm/gems/ruby-2.0.0-p247/gems/capistrano-3.0.0/lib/capistrano/setup.rb:12:in `load'
/Users/justin/.rvm/gems/ruby-2.0.0-p247/gems/capistrano-3.0.0/lib/capistrano/setup.rb:12:in `block (2 levels) in <top (required)>'
/Users/justin/.rvm/gems/ruby-2.0.0-p247/gems/capistrano-3.0.0/lib/capistrano/application.rb:12:in `run'
/Users/justin/.rvm/gems/ruby-2.0.0-p247/gems/capistrano-3.0.0/bin/cap:3:in `<top (required)>'
/Users/justin/.rvm/gems/ruby-2.0.0-p247/bin/cap:23:in `load'
/Users/justin/.rvm/gems/ruby-2.0.0-p247/bin/cap:23:in `<main>'
Tasks: TOP => sandbox
```
