### ISSUE TITLE
 undefined method `skip_during' for Bundler::RubygemsIntegration::Deprecate:Class (NoMethodError)

### ISSUE THREAD

**Issue by pweaver** [bundler/bundler#2232]
During the rails initialization newer versions of rubygems attempts to call Gems.skip_during (Gems is refering to Bundler::RubygemsIntegration::Deprecate) and it can't find skip_during. This appears to be because skip during is defined as a method in a class in lib/bundler/deprecate.rb, and as a module method in ruby gems. 

rubygems:

module Deprecate  
...
 def skip_during
      Gem::Deprecate.skip, original = true, Gem::Deprecate.skip
      yield
    ensure
      Gem::Deprecate.skip = original
    end
...
module_function :deprecate, :skip_during

In my boot.rb fine doing 
require 'rubygems'

```
    # Patch Bundler so it doesn't break on newer ruby gems
    if ruby_release =~ /1\.9\.1/
      Bundler::RubygemsIntegration::Deprecate.class_eval do
```
# def self.skip_during; yield; end

```
      end
    end
```

fixes the issue.

Issue with rails 2.3.8, ruby 1.9.1
Works fine with ruby 1.9.2
